# Generated by Django 2.1.4 on 2018-12-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181207_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='opcao_escolha',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='questao',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='votos',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='text',
            new_name='texto',
        ),
    ]
