# Generated by Django 2.1.4 on 2018-12-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181211_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questao',
            new_name='poll',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votos',
        ),
    ]
