# Generated by Django 2.1.4 on 2018-12-12 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20181212_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='autor',
            field=models.ForeignKey(default=1994, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
